services:
  db:
    image: postgres:15  # Assuming this is your custom PostgreSQL image
    restart: always
    env_file:
      - .env
    container_name: dwh
    environment:
      POSTGRES_USER: ${WAREHOUSE_USER}  # Correct environment variable for Postgres
      POSTGRES_PASSWORD: ${WAREHOUSE_PASSWORD}
      POSTGRES_DB: ${WAREHOUSE_NAME}
    volumes:
      - db:/var/lib/postgresql/data  # Persist database data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialize with SQL script

  dash_app:
    build:
      context: .  # Build the Dash app from the current directory
      dockerfile: Dockerfile  # Use the Dockerfile in the current directory
    container_name: dash_app
    restart: always
    depends_on:
      - db  # Ensures the database service starts before the Dash app
    ports:
      - "8050:8050"  # Expose Dash app on port 8050


volumes:
  db:
    driver: local  # Persist the database using a local volume
